### ISSUE TITLE
test_slidingContact fails

### ISSUE THREAD

**Issue by markus-stoll** [CognitionGuidedSurgery/msml#208]
======================================================================
ERROR: test_slidingContact (msmltest.SlidingContactTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/msml/src/msmltest/slidingContact.py", line 19, in test_slidingContact
    mem = self.app.execute_msml(self.mf, )
  File "/home/ubuntu/msml/src/msml/frontend.py", line 427, in execute_msml
    exe = self.get_executor(msml_file)
  File "/home/ubuntu/msml/src/msml/frontend.py", line 376, in get_executor
    self._prepare_msml_model(msml_file)
  File "/home/ubuntu/msml/src/msml/frontend.py", line 397, in _prepare_msml_model
    exporter = self.exporter(mfile)
  File "/home/ubuntu/msml/src/msml/exporter/sofanew.py", line 72, in __init__
    features=SOFA_EXPORTER_FEATURES
  File "/home/ubuntu/msml/src/msml/exporter/base.py", line 115, in initialize
    self.gather_inputs()
  File "/home/ubuntu/msml/src/msml/exporter/base.py", line 231, in gather_inputs
    register_constraints()
  File "/home/ubuntu/msml/src/msml/exporter/base.py", line 206, in register_constraints
    "parameter %s of constraint %s has not proper value" % (para.name, const.id))
MSMLError: parameter pulse of constraint id23 has not proper value
-------------------- >> begin captured logging << --------------------

**Comment by dschauba** [comment]
Yeah, i added a switch to surfacePressureOnMesh which allows enabling and disabling of pulseMode.
I forgot to adjust test appropriately.
