### ISSUE TITLE
DLL not found on workflow with variadic arguments

### ISSUE THREAD

**Issue by dschauba** [CognitionGuidedSurgery/msml#215]
Running a workflow with variadics, for some workflows these errors are thrown:
```python
INFO     RDFLib Version: 4.1.2
Process PoolWorker-1:
Traceback (most recent call last):
  File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python27\lib\multiprocessing\pool.py", line 102, in worker
    task = get()
  File "C:\Python27\lib\multiprocessing\queues.py", line 376, in get
    return recv()
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
INFO     RDFLib Version: 4.1.2
Process PoolWorker-2:
Traceback (most recent call last):
  File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python27\lib\multiprocessing\pool.py", line 102, in worker
    task = get()
  File "C:\Python27\lib\multiprocessing\queues.py", line 376, in get
    return recv()
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
INFO     RDFLib Version: 4.1.2
Process PoolWorker-3:
Traceback (most recent call last):
  File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python27\lib\multiprocessing\pool.py", line 102, in worker
    task = get()
  File "C:\Python27\lib\multiprocessing\queues.py", line 376, in get
    return recv()
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
INFO     RDFLib Version: 4.1.2
Process PoolWorker-4:
Traceback (most recent call last):
  File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python27\lib\multiprocessing\pool.py", line 102, in worker
    task = get()
  File "C:\Python27\lib\multiprocessing\queues.py", line 376, in get
    return recv()
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
INFO     RDFLib Version: 4.1.2
Process PoolWorker-5:
Traceback (most recent call last):
  File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python27\lib\multiprocessing\pool.py", line 102, in worker
    task = get()
  File "C:\Python27\lib\multiprocessing\queues.py", line 376, in get
    return recv()
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
```
Workflow is:
```xml
<ACVDReduceSurfaceMesh id="acvdreduce" inputMeshFile="meshed_forces_volume.vtk_*.vtk"
											   outputMeshFile="acvd_remeshed_*.vtk"
											   verticesCount="2000"
											   forceManifold="false"
											   asciiOutput="false" />		
		<!-- smooth them  -->	
		<vtkSmoothMesh id="smooth" mesh="${acvdreduce}" targetSurfaceMeshFilename="smoothed_new_*.vtk" iterations="15" 
					   featureAngle="12" passBand="0.001" boundarySmoothing="false" featureEdgeSmoothing="false"
					   nonManifoldSmoothing="false" normalizedCoordinates="true"/>				   
		<!-- mesh with tetgen -->  
		<TetgenCreateVolumeMesh id="VolumeForcesMesher2" targetMeshFilename="tetmesh_new_*.vtk"
								surfaceMesh="${smooth}" preserveBoundary="0" />				
		
```

**Comment by markus-stoll** [comment]
Does it work in single core mode? Whats the error message there?
You can use the seq_parallel parameter of App.__init in frontend.py to use single core mode or add  an argument to create_argument_parser() and define it from command line.

**Comment by markus-stoll** [comment]
Does it work with none-variadic args?

**Comment by dschauba** [comment]
Ok, will try.
Jep, works with non-variadics.
vtkSmoothMesh and TetgenCreateVolumeMesh can be chained, too (with variadics).
Only the ACVDReduceSurfaceMesh-Operator does not like variadics, it seems.

**Comment by areku** [comment]
Is the environment inherited? Also `%PATH`

**Comment by dschauba** [comment]
Will check

**Comment by markus-stoll** [comment]
does it work now?

**Comment by dschauba** [comment]
Sorry, changed the workflow. Could not reproduce this error, probably was a user fault somewhere. ;)
Will close this now and reopen, if it reoccurs.
