### ISSUE TITLE
Release 0.9

### ISSUE THREAD

**Issue by markus-stoll** [CognitionGuidedSurgery/msml#219]
As discussed we want to publish a 'stable' realease version 0.9. 
I have merged the latest experimental to master (55600ea248bedb8f3dfeedab9cd1248718b9970b)

Please do some testing on this version but do not change any code unless it is really necessary.

**Comment by markus-stoll** [comment]
new release branch: release_cand_1.0

**Comment by markus-stoll** [comment]
Installation problems with pip:


F:\dev\msml_exp>C:\python27\Scripts\pip.exe install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): lxml in c:\python27\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): path.py in c:\python27\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): networkx in c:\python27\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): simplegeneric in c:\python27\lib\site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): jinja2 in c:\python27\lib\site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): rdflib in c:\python27\lib\site-packages (from -r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): colorama in c:\python27\lib\site-packages (from -r requirements.txt (line 12))
Collecting pyyaml (from -r requirements.txt (line 21))
  Using cached PyYAML-3.11.tar.gz
Collecting addict (from -r requirements.txt (line 22))
  Using cached addict-0.4.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): decorator>=3.4.0 in c:\python27\lib\site-packages (from networkx->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): markupsafe in c:\python27\lib\site-packages (from jinja2->-r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): isodate in c:\python27\lib\site-packages (from rdflib->-r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): pyparsing in c:\python27\lib\site-packages (from rdflib->-r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): SPARQLWrapper in c:\python27\lib\site-packages (from rdflib->-r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): html5lib in c:\python27\lib\site-packages (from rdflib->-r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): six in c:\python27\lib\site-packages (from html5lib->rdflib->-r requirements.txt (line 10))
Installing collected packages: pyyaml, addict
  Running setup.py install for pyyaml
    Complete output from command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\stoll\\appdata\\local\\temp\\pip-build-xtenkd\\pyya
ml\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\stoll\appdata\l
ocal\temp\pip-zelahe-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\yaml
    copying lib\yaml\composer.py -> build\lib.win-amd64-2.7\yaml
    copying lib\yaml\constructor.py -> build\lib.win-amd64-2.7\yaml
    copying lib\yaml\cyaml.py -> build\lib.win-amd64-2.7\yaml
    copying lib\yaml\dumper.py -> build\lib.win-amd64-2.7\yaml
    copying lib\yaml\emitter.py -> build\lib.win-amd64-2.7\yaml
    copying lib\yaml\error.py -> build\lib.win-amd64-2.7\yaml
    copying lib\yaml\events.py -> build\lib.win-amd64-2.7\yaml
    copying lib\yaml\loader.py -> build\lib.win-amd64-2.7\yaml
    copying lib\yaml\nodes.py -> build\lib.win-amd64-2.7\yaml
    copying lib\yaml\parser.py -> build\lib.win-amd64-2.7\yaml
    copying lib\yaml\reader.py -> build\lib.win-amd64-2.7\yaml
    copying lib\yaml\representer.py -> build\lib.win-amd64-2.7\yaml
    copying lib\yaml\resolver.py -> build\lib.win-amd64-2.7\yaml
    copying lib\yaml\scanner.py -> build\lib.win-amd64-2.7\yaml
    copying lib\yaml\serializer.py -> build\lib.win-amd64-2.7\yaml
    copying lib\yaml\tokens.py -> build\lib.win-amd64-2.7\yaml
    copying lib\yaml\__init__.py -> build\lib.win-amd64-2.7\yaml
    running build_ext
    creating build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\Release
    checking if libyaml is compilable
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\stoll\appdata\local\temp\pip-build-xtenkd\pyyaml\setup.py", line 342, in <module>
        'test': test,
      File "C:\Python27\lib\distutils\core.py", line 152, in setup
        dist.run_commands()
      File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "C:\Python27\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Python27\lib\distutils\command\install.py", line 563, in run
        self.run_command('build')
      File "C:\Python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "C:\Python27\lib\distutils\command\build.py", line 127, in run
        self.run_command(cmd_name)
      File "C:\Python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\users\stoll\appdata\local\temp\pip-build-xtenkd\pyyaml\setup.py", line 169, in run
        _build_ext.run(self)
      File "C:\Python27\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "c:\users\stoll\appdata\local\temp\pip-build-xtenkd\pyyaml\setup.py", line 211, in build_extensions
        with_ext = self.check_extension_availability(ext)
      File "c:\users\stoll\appdata\local\temp\pip-build-xtenkd\pyyaml\setup.py", line 237, in check_extension_availability
        depends=ext.depends)
      File "C:\Python27\lib\distutils\msvc9compiler.py", line 473, in compile
        self.initialize()
      File "C:\Python27\lib\distutils\msvc9compiler.py", line 383, in initialize
        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "C:\Python27\lib\site-packages\setuptools\msvc9_support.py", line 52, in query_vcvarsall
        return unpatched['query_vcvarsall'](version, *args, **kwargs)
      File "C:\Python27\lib\distutils\msvc9compiler.py", line 299, in query_vcvarsall
        raise ValueError(str(list(result.keys())))
    ValueError: [u'path']

    ----------------------------------------
    Command "C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\stoll\\appdata\\local\\temp\\pip-build-xtenkd\\pyyaml\\setup.py';exec(c
ompile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\stoll\appdata\local\temp\pip-zelahe
-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\stoll\appdata\local\temp\pip-build-xtenkd\pyyaml

**Comment by markus-stoll** [comment]
pyyaml should be installed from binaries (without pip) - wiki was updated.
