### ISSUE TITLE
Infinite recursion on variadic arguments?

### ISSUE THREAD

**Issue by dschauba** [CognitionGuidedSurgery/msml#220]
Getting an infinite recursion when using variadic arguments:
```python
INFO     RDFLib Version: 4.1.2
CRITICAL Slot pulse in parent surfacePressureOnMesh does not have a physical type defined. This can cause conversion errors.
ERROR    msml.ext.misc.AllIndicesFromMesh is not available (function/attribute not found), got exception message ''module' object has no attribute 'AllIndicesFromMesh'
ERROR    msml.ext.misc.MergeCompleteMeshes is not available (function/attribute not found), got exception message ''module' object has no attribute 'MergeCompleteMeshes'
ERROR    msml.ext.misc.RenameDataArray is not available (function/attribute not found), got exception message ''module' object has no attribute 'RenameDataArray'
ERROR    msml.ext.misc.ShrinkMesh is not available (function/attribute not found), got exception message ''module' object has no attribute 'ShrinkMesh'
ERROR    MiscPython Operators unavaiable because of ImportError: No module named scipy
ERROR    msml.ext.misc_python.copy_file is not available (function/attribute not found), got exception message ''module' object has no attribute 'copy_file'
ERROR    msml.ext.misc_python.generateBeamDisplacementsFromParaCoeffs is not available (function/attribute not found), got exception message ''module' object has no attribute 'generateBeamDisplacementsFromParaCoeffs'
ERROR    msml.ext.misc_python.generateBeamDisplacementsFromSplineCoeffs is not available (function/attribute not found), got exception message ''module' object has no attribute 'generateBeamDisplacementsFromSplineCoeffs'
ERROR    msml.ext.vtuToHf3inpWithBdyFacetMatIDsProducer.vtu_To_Hf3inpWithBdyFacetMatID_Producer is not available (module not found), got exception message 'No module named vtk'
CRITICAL Could not import vtk python module. Did you install python-vtk?
ERROR    msml.ext.msmlvtk.closest_point is not available (function/attribute not found), got exception message ''module' object has no attribute 'closest_point'
ERROR    msml.ext.xnat.xnat_get is not available (module not found), got exception message 'No module named requests'
ERROR    msml.ext.xnat.xnat_put is not available (module not found), got exception message 'No module named requests'
INFO     gunzip -c "C:\msmldev\msml\examples\SlidingContactPat\patgeom_tumor_t8.ctx.gz" >"C:\msmldev\msml\examples\SlidingContactPat\patgeom_tumor_t8.ctx"
DEBUG    error occurred but was silently disposed: ERROR: In ..\..\..\IO\Image\vtkImageReader2.cxx, line 628
vtkImageReader2 (0000000008C955F0): Initialize: Could not open file 


ERROR    GetNumberOfTuples()=24641536
image->size()=24641536
wdim=1
DEBUG    selecting started...
DEBUG    selecting cells of id: 5
DEBUG    There are 1478 cells after thresholding with 5
DEBUG    saving...
DEBUG    selecting finished
DEBUG    CellType is 5
INFO     RDFLib Version: 4.1.2
Process PoolWorker-1:
Traceback (most recent call last):
  File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python27\lib\multiprocessing\pool.py", line 102, in worker
    task = get()
  File "C:\Python27\lib\multiprocessing\queues.py", line 376, in get
    return recv()
  File "C:\msmldev\msml\src\msml\model\alphabet\__init__.py", line 322, in __getattr__
    if item in self.meta:
  File "C:\msmldev\msml\src\msml\model\alphabet\__init__.py", line 322, in __getattr__
    if item in self.meta:
  File "C:\msmldev\msml\src\msml\model\alphabet\__init__.py", line 322, in __getattr__
    if item in self.meta:
  File "C:\msmldev\msml\src\msml\model\alphabet\__init__.py", line 322, in __getattr__
    if item in self.meta:
  File "C:\msmldev\msml\src\msml\model\alphabet\__init__.py", line 322, in __getattr__
    if item in self.meta:
  File "C:\msmldev\msml\src\msml\model\alphabet\__init__.py", line 322, in __getattr__
    if item in self.meta:
  File "C:\msmldev\msml\src\msml\model\alphabet\__init__.py", line 322, in __getattr__
    if item in self.meta:
  File "C:\msmldev\msml\src\msml\model\alphabet\__init__.py", line 322, in __getattr__
    if item in self.meta:
```
Workflow is like this:
```xml
<CGALMeshVolumeFromVoxels id="TumorMesher" meshFilename="tumor_meshed.vtk" 
								  image="patgeom_tumor_t8.ctx.gz"
								  facetAngle="15" facetSize="4" facetDistance="3" cellSize="10"
								  cellRadiusEdgeRatio="3"  odt="false" lloyd="false" pertube="false"				  
								  exude="false"/>
		<SelectVolumesByMaterialID id="TumorSelect" selectedVolumesFilename="tumor_extract.vtk" 
										mesh="${TumorMesher}" group="5"/>	
		<ExtractSurfaceMesh id="TumorSurfacePresim"  
							mesh="${TumorSelect}" targetSurfaceMeshFilename="tumor_surface_presim.vtk"/>	
							
							
		<!-- Transform tumor mesh 		-->		  
		<TransformMeshBarycentric id="bary" volumeMeshToDeform="${TumorSelect}" referenceVolumeMesh="out_cgal_rips/moving_fem_split.vtk"
								  deformedVolumeMesh="out_cgal_rips/movingMeshA*.vtu" targetVolumeMesh="deformed_tumor_meshes*.vtk"/>	
```

In experimental_win_ok-Branch, this workflow snippet worked.

**Comment by dschauba** [comment]
Variables during loop:

![loopbug](https://cloud.githubusercontent.com/assets/854277/6189377/676de8d6-b39a-11e4-8f95-b06d1979ef7d.PNG)

**Comment by areku** [comment]
Test the fix.

**Comment by dschauba** [comment]
On master, i get:
```python
Process PoolWorker-2:
Traceback (most recent call last):
  File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python27\lib\multiprocessing\pool.py", line 102, in worker
    task = get()
  File "C:\Python27\lib\multiprocessing\queues.py", line 376, in get
    return recv()
  File "C:\msmldev\msml\src\msml\model\alphabet\__init__.py", line 322, in __getattr__
    if meta in self.__dict__ and item in self.meta:
NameError: global name 'meta' is not defined
```

**Comment by dschauba** [comment]
Using self.meta, the endless recursion appears again, damn!

**Comment by areku** [comment]
I forgotten the quotes.

**Comment by dschauba** [comment]
YES! Looks good now.
Thanks for quick help!
