### ISSUE TITLE
Optional arguments in constraint alphabet file

### ISSUE THREAD

**Issue by dschauba** [CognitionGuidedSurgery/msml#221]
I specified an argument of a constraint, which i would like to be optional, like this:
```xml
<arg name="speed" physical="float" logical="Scalar" optional="true" default="-1">
     <meta key="doc" value="Set speed of pressure application (Quoting SOFA-Comment: Continuous pressure application in Pascal per second. Only active in pulse model.)"/>
</arg>	
```
While registering constraints in register_constraint-Method (exporter/base.py line: 192), an error is thrown 
```

Traceback (most recent call last):
  File "C:\Users\schaub\Desktop\eclipse\plugins\org.python.pydev_3.8.0.201409251235\pysrc\pydevd.py", line 2183, in <module>
    globals = debugger.run(setup['file'], None, None)
  File "C:\Users\schaub\Desktop\eclipse\plugins\org.python.pydev_3.8.0.201409251235\pysrc\pydevd.py", line 1622, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\msmldev\msml\src\msml.py", line 36, in <module>
    msml.frontend.main()
  File "C:\msmldev\msml\src\msml\frontend.py", line 625, in main
    app._exec()
  File "C:\msmldev\msml\src\msml\frontend.py", line 599, in _exec
    COMMANDS[cmd]()
  File "C:\msmldev\msml\src\msml\frontend.py", line 506, in execution
    self.execute_msml_file(path(fil))
  File "C:\msmldev\msml\src\msml\frontend.py", line 496, in execute_msml_file
    return self.execute_msml(mfile)
  File "C:\msmldev\msml\src\msml\frontend.py", line 499, in execute_msml
    exe = self.get_executor(msml_file)
  File "C:\msmldev\msml\src\msml\frontend.py", line 448, in get_executor
    self._prepare_msml_model(msml_file)
  File "C:\msmldev\msml\src\msml\frontend.py", line 469, in _prepare_msml_model
    exporter = self.exporter(mfile)
  File "C:\msmldev\msml\src\msml\exporter\sofanew.py", line 72, in __init__
    features=SOFA_EXPORTER_FEATURES
  File "C:\msmldev\msml\src\msml\exporter\base.py", line 115, in initialize
    self.gather_inputs()
  File "C:\msmldev\msml\src\msml\exporter\base.py", line 231, in gather_inputs
    register_constraints()
  File "C:\msmldev\msml\src\msml\exporter\base.py", line 206, in register_constraints
    "parameter %s of constraint %s has not proper value" % (para.name, const.id))
msml.exceptions.MSMLError: parameter speed of constraint id1 has not proper value
```
Since a default value is given in definition of argument "speed", i wonder if this is a bug?

**Comment by markus-stoll** [comment]
I guess its not an operator but part of a constraint - maybe defaults are only implemented for operators?

**Comment by dschauba** [comment]
Yeah, forgot that, it´s a constraint!
So, no defaults for constraints allowed?

**Comment by markus-stoll** [comment]
That must be implemented first. I think it would be nice to have.

**Comment by dschauba** [comment]
Should do?
