### ISSUE TITLE
Error using variadic arguments 

### ISSUE THREAD

**Issue by dschauba** [CognitionGuidedSurgery/msml#222]
Following line produces errors if variadic arguments are used (alphabet/__init__.py line: 325):
```python
return self.__dict__[item]
```

Error is: 
```python
Process PoolWorker-1:
Traceback (most recent call last):
  File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python27\lib\multiprocessing\pool.py", line 102, in worker
    task = get()
  File "C:\Python27\lib\multiprocessing\queues.py", line 376, in get
    return recv()
  File "C:\msmldev\msml\src\msml\model\alphabet\__init__.py", line 325, in __getattr__
    return self.__dict__[item]
KeyError: '__setstate__'
```

Sorry to bother again, but i don´t understand how stuff works in alphabet-Module.

**Comment by areku** [comment]
Change the line to the [old version](https://github.com/CognitionGuidedSurgery/msml/commit/6d1dfe643fc8fcd4f9978dbe58a6609882943cc4):

```
return super(Slot, self).__getattr__(item)
```

It's funny how `multiprocessing` breaks Python code.

**Comment by dschauba** [comment]
Thank you again!
