### ISSUE TITLE
MiscPython Operators: failed to load dll.

### ISSUE THREAD

**Issue by markus-stoll** [CognitionGuidedSurgery/msml#238]
```
ERROR    MiscPython Operators unavaiable because of ImportError: DLL load failed: %1 ist keine zulõssige Win32-Anwendung.
ERROR    msml.ext.misc_python.copy_file is not available (function/attribute not found), got exception message ''module' object has no attribute 'copy_file'
ERROR    msml.ext.misc_python.generateBeamDisplacementsFromParaCoeffs is not available (function/attribute not found), got exception message ''module' object ha
s no attribute 'generateBeamDisplacementsFromParaCoeffs'
ERROR    msml.ext.misc_python.generateBeamDisplacementsFromSplineCoeffs is not available (function/attribute not found), got exception message ''module' object
has no attribute 'generateBeamDisplacementsFromSplineCoeffs'
ERROR    Parameter name of Element mass is not specified in definition.
ERROR    Parameter forStep of Element fixedConstraint is not specified in definition.
ERROR    Parameter name of Element fixedConstraint is not specified in definition.
ERROR    Parameter name of Element displacementConstraint is not specified in definition.
ERROR    Parameter forStep of Element displacementConstraint is not specified in definition.
ERROR    some features are not supported by exporter
ERROR    -- msml_file: set(['object_element_displacement_supported', 'output_supported', 'object_element_mass_supported', 'scene_objects_supported', 'constraint
s_supported', 'env_processingunit_CPU_supported', 'material_region_supported', 'env_linearsolver_iterativeCG_supported', 'env_preconditioner_None_supported', 'o
bject_element_linearElasticMaterial_supported', 'sets_elements_supported', 'object_element_displacementConstraint_supported', 'sets_nodes_supported', 'environme
nt_simulation_steps_supported', 'object_element_fixedConstraint_supported', 'env_timeintegration_dynamicImplicitEuler_supported'])
ERROR    -- supported: frozenset(['object_element_displacement_supported', 'output_supported', 'object_element_mass_supported', 'env_processingunit_CPU_supporte
d', 'constraints_supported', 'material_region_supported', 'env_linearsolver_iterativeCG_supported', 'env_preconditioner_None_supported', 'object_element_linearE
lasticMaterial_supported', 'scene_objects_supported', 'env_timeintegration_dynamicImplicitEuler_supported', 'sets_surface_supported', 'sets_elements_supported',
 'environment_simulation_steps_supported', 'object_element_fixedConstraint_supported', 'sets_nodes_supported'])
ERROR    -- not matched: set(['object_element_displacementConstraint_supported'])
ERROR    487 points found in box
ERROR    24 points found in box
ERROR    24 points found in box
ERROR    msml.ext.misc_python.copy_file is not available (function/attribute not found), got exception message ''module' object has no attribute 'copy_file'
Traceback (most recent call last):
  File "F:\dev\msml_exp\src\msml.py", line 36, in <module>
    msml.frontend.main()
  File "F:\dev\msml_exp\src\msml\frontend.py", line 628, in main
    app._exec()
  File "F:\dev\msml_exp\src\msml\frontend.py", line 602, in _exec
    COMMANDS[cmd]()
  File "F:\dev\msml_exp\src\msml\frontend.py", line 508, in execution
    self.execute_msml_file(path(fil))
  File "F:\dev\msml_exp\src\msml\frontend.py", line 498, in execute_msml_file
    return self.execute_msml(mfile)
  File "F:\dev\msml_exp\src\msml\frontend.py", line 502, in execute_msml
    mem = exe.run()
  File "F:\dev\msml_exp\src\msml\run\__init__.py", line 171, in run
    self._execute_operator_task(node)
  File "F:\dev\msml_exp\src\msml\run\__init__.py", line 191, in _execute_operator_task
    new = ExecutorsHelper.execute_operator_task(self._memory, task)
  File "F:\dev\msml_exp\src\msml\run\__init__.py", line 425, in execute_operator_task
    result = task.operator(**kwargs)
  File "F:\dev\msml_exp\src\msml\model\alphabet\operator\python.py", line 54, in __call__
    r = self._function(*args)
TypeError: 'NoneType' object is not callable
```

**Comment by markus-stoll** [comment]
MiscPython uses SciPy . SciPy is available in 32bit an 64bit - make sure you use the correct one.
